spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # Affiche les requêtes SQL dans la console
    properties:
      hibernate.format_sql: false
  profiles:
    active: dev

server:
  port: 8081
